"""update chunks page numbers and section title

Revision ID: 2925ca44ac4a
Revises: 5cbb57bed3b9
Create Date: 2026-01-26 12:13:30.252172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2925ca44ac4a'
down_revision: Union[str, None] = '5cbb57bed3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('section_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'section_title')
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###
