"""update chunks for BM25

Revision ID: 5cbb57bed3b9
Revises: ef2440c5d603
Create Date: 2026-01-25 20:08:17.790011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5cbb57bed3b9"
down_revision: Union[str, None] = "ef2440c5d603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1️⃣ Add tsvector column
    op.add_column("chunks", sa.Column("tsv", postgresql.TSVECTOR(), nullable=True))

    # 2️⃣ Backfill existing rows
    op.execute(
        """
        UPDATE chunks
        SET tsv = to_tsvector('english', content)
        """
    )

    # 3️⃣ Create trigger function
    op.execute(
        """
        CREATE FUNCTION chunks_tsv_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.tsv :=
                to_tsvector('english', COALESCE(NEW.content, ''));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )

    # 4️⃣ Attach trigger
    op.execute(
        """
        CREATE TRIGGER chunks_tsv_update
        BEFORE INSERT OR UPDATE ON chunks
        FOR EACH ROW EXECUTE FUNCTION chunks_tsv_trigger();
        """
    )

    # 5️⃣ Create GIN index
    op.execute(
        """
        CREATE INDEX idx_chunks_tsv
        ON chunks
        USING GIN(tsv);
        """
    )

    # modify column to set NOT NULL constraint
    op.alter_column("chunks", "tsv", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_chunks_tsv")
    op.execute("DROP TRIGGER IF EXISTS chunks_tsv_update ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_tsv_trigger")
    op.drop_column("chunks", "tsv")
    # ### end Alembic commands ###
