"""update status lookup

Revision ID: 8b32605f4a54
Revises: d71428325f6f
Create Date: 2025-12-29 12:46:56.327420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b32605f4a54'
down_revision: Union[str, None] = 'd71428325f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_statuses', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_statuses', 'description')
    # ### end Alembic commands ###
