"""update documents retry logic

Revision ID: a3c79f4c33d5
Revises: 8b32605f4a54
Create Date: 2025-12-30 18:33:05.718245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c79f4c33d5'
down_revision: Union[str, None] = '8b32605f4a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_error')
    op.drop_column('documents', 'max_retries')
    op.drop_column('documents', 'retry_count')
    # ### end Alembic commands ###
