"""update chunks unique constraint

Revision ID: bbd130e1a154
Revises: a3c79f4c33d5
Create Date: 2025-12-30 19:49:58.870075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd130e1a154'
down_revision: Union[str, None] = 'a3c79f4c33d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chunks', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='unique')
    # ### end Alembic commands ###
