"""update documents and create status lookup

Revision ID: d71428325f6f
Revises: a4c471be243c
Create Date: 2025-12-29 12:36:08.741692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71428325f6f'
down_revision: Union[str, None] = 'a4c471be243c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_statuses',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('documents', sa.Column('storage_provider', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('storage_bucket', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('storage_key', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('status_id', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(None, 'documents', 'document_statuses', ['status_id'], ['id'])
    op.drop_column('documents', 's3_key')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 's3_bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_bucket', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'status_id')
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'storage_bucket')
    op.drop_column('documents', 'storage_provider')
    op.drop_table('document_statuses')
    # ### end Alembic commands ###
