"""create query audit

Revision ID: ef2440c5d603
Revises: e6fbb049c92a
Create Date: 2026-01-21 19:44:33.246661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef2440c5d603'
down_revision: Union[str, None] = 'e6fbb049c92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('rag_mode', sa.String(length=32), nullable=False),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_audit_created_at'), 'query_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_audit_user_id'), 'query_audit', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_audit_user_id'), table_name='query_audit')
    op.drop_index(op.f('ix_query_audit_created_at'), table_name='query_audit')
    op.drop_table('query_audit')
    # ### end Alembic commands ###
